name = "RealisticCraft"
author = "Brynley Llewellyn-Roux"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "198770403c76af6ac02d7cc8cf77a4cf1df40acfa540b1dc38b6fca6d247d67b"

[versions]
fabric = "0.14.10"
minecraft = "1.19"
